# Generated by Django 5.1.3 on 2024-12-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Alcohol by Volume (%)'),
        ),
    ]
