# Generated by Django 5.1.3 on 2024-11-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('shaken', 'Shaken'), ('stirred', 'Stirred'), ('built', 'Built'), ('frozen', 'Frozen'), ('blended', 'Blended')], max_length=10)),
                ('style', models.CharField(choices=[('tiki', 'Tiki'), ('modern', 'Modern'), ('sour', 'Sour')], max_length=10)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('slice', 'Slice'), ('wedge', 'Wedge'), ('drop', 'Drop'), ('dash', 'Dash'), ('millimeter', 'Millimeter'), ('ounce', 'Ounce'), ('cup', 'Cup')], max_length=20)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cocktails.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
            ],
        ),
    ]
