# Generated by Django 5.1.3 on 2024-12-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
