# Generated by Django 5.1.3 on 2024-12-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_creator'),
        ('ingredients', '0002_alter_ingredient_abv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='style',
            field=models.CharField(blank=True, choices=[('tiki', 'Tiki'), ('modern', 'Modern'), ('sour', 'Sour')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='type',
            field=models.CharField(blank=True, choices=[('shaken', 'Shaken'), ('stirred', 'Stirred'), ('built', 'Built'), ('frozen', 'Frozen'), ('blended', 'Blended')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('slice', 'Slice'), ('wedge', 'Wedge'), ('drop', 'Drop'), ('dash', 'Dash'), ('milliliter', 'Milliliter'), ('ounce', 'Ounce'), ('cup', 'Cup')], max_length=20, null=True),
        ),
    ]
