# Generated by Django 5.1.3 on 2024-12-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_alter_cocktail_instructions_alter_cocktail_style_and_more'),
        ('ingredients', '0002_alter_ingredient_abv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
            preserve_default=False,
        ),
    ]
