# Generated by Django 5.1.3 on 2024-12-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_cocktailingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('Slice', 'slice'), ('Wedge', 'wedge'), ('Drop', 'drop'), ('Dash', 'dash'), ('Milliliter', 'ml'), ('Ounce', 'oz'), ('Cup', 'c')], max_length=20, null=True),
        ),
    ]
